version: "{build}"
platform:
  - x64
test: off

clone_folder: c:\gopath\src\github.com\regner\albionmarket-client

skip_non_tags: true

environment:
  GOPATH: c:\gopath
  
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;%PATH%
  - go version
  - go env
  - gcc --version
  - g++ --version
  # WinPcap setup
  - choco install winpcap
  - appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
  - 7z x .\WpdPack_4_1_2.zip -oc:\
  # Wix setup
  - curl -fsSL -o C:\wix310-binaries.zip http://static.wixtoolset.org/releases/v3.10.3.3007/wix310-binaries.zip
  - 7z x C:\wix310-binaries.zip -y -r -oC:\wix310
  - set PATH=C:\wix310;%PATH%
  # Go-MSI setup
  - curl -fsSL -o C:\go-msi.msi https://github.com/mh-cbon/go-msi/releases/download/1.0.1/go-msi-amd64.msi
  - msiexec.exe /i C:\go-msi.msi /quiet
  - set PATH=C:\Program Files\go-msi\;%PATH%
 
build_script:
  - go get
  - set APPNAME=albionmarket-client
  - set GOARCH=amd64
  - go build -o %APPNAME%.exe --ldflags "-X main.VERSION=%APPVEYOR_REPO_TAG_NAME%" main.go
  - go-msi.exe make --msi %APPVEYOR_BUILD_FOLDER%\%APPNAME%-%GOARCH%.msi --version %APPVEYOR_REPO_TAG_NAME%

artifacts:
  - path: '*-amd64.msi'
    name: msi-x64

deploy:
  - provider: GitHub
    artifact: msi-x64
    draft: false
    prerelease: false
    description: "Release {APPVEYOR_REPO_TAG_NAME}"
    auth_token:
      secure: IHVtIm5+rczNXbo3HeUlsV+/z72pNbl0DNXs1mRHCbHiqf/j0DUVNW9Lg3CYBlX+
    on:
      branch:
        - master
        - /v\d\.\d\.\d/
        - /\d\.\d\.\d/
      appveyor_repo_tag: true
